/**
 * Shared ResearchPaper type used by all agents and tools.
 *
 * Every academic search tool returns results conforming to this interface.
 * All 5 agents consume and produce data using this shape.
 */
export interface ResearchPaper {
  /** Unique identifier from the source (e.g. OpenAlex work ID) */
  id: string;

  /** Paper title */
  title: string;

  /** List of author names */
  authors: string[];

  /** Paper abstract, null if unavailable */
  abstract: string | null;

  /** Publication year, null if unavailable */
  year: number | null;

  /** Digital Object Identifier, null if unavailable */
  doi: string | null;

  /** Number of citations */
  citationCount: number;

  /** URL to the paper's landing page, null if unavailable */
  url: string | null;

  /** Direct URL to PDF, null if unavailable */
  pdfUrl: string | null;

  /** Whether the paper is open access */
  isOpenAccess: boolean;

  /** Source that returned this result (e.g. "OpenAlex", "SemanticScholar") */
  source: string;
}

/**
 * Output shape for the Query & Search Agent.
 */
export interface QuerySearchResult {
  /** The original user query */
  query: string;

  /** Search queries generated by the agent */
  searchQueries: string[];

  /** Deduplicated list of papers found */
  papers: ResearchPaper[];

  /** Errors encountered during search (non-fatal) */
  errors?: string[];
}
