/**
 * Content status indicating what level of text content was retrieved.
 */
export type ContentStatus = "metadata_only" | "abstract_only" | "full_text";

/**
 * Represents a text chunk prepared for vector indexing / RAG retrieval.
 */
export interface PaperChunk {
  /** Sequential index of the chunk within the paper */
  chunkIndex: number;

  /** Chunk text content */
  text: string;

  /** Approximate token count */
  tokenCount?: number;

  /** Metadata for RAG / vector citation and filtering */
  metadata: {
    paperId: string;
    paperTitle: string;
    source: string;
    doi?: string | null;
    year?: number | null;
    isAbstract?: boolean;
    pageNumber?: number;
  };
}

/**
 * Shared ResearchPaper type used by all agents and tools.
 *
 * Every academic search tool returns results conforming to this interface.
 * All agents consume and produce data using this shape.
 */
export interface ResearchPaper {
  /** Unique identifier from the source (e.g. OpenAlex work ID) */
  id: string;

  /** Paper title */
  title: string;

  /** List of author names */
  authors: string[];

  /** Paper abstract, null if unavailable */
  abstract: string | null;

  /** Publication year, null if unavailable */
  year: number | null;

  /** Digital Object Identifier, null if unavailable */
  doi: string | null;

  /** Number of citations */
  citationCount: number;

  /** URL to the paper's landing page, null if unavailable */
  url: string | null;

  /** Direct URL to PDF, null if unavailable */
  pdfUrl: string | null;

  /** Whether the paper is open access */
  isOpenAccess: boolean;

  /** Source that returned this result (e.g. "OpenAlex", "SemanticScholar") */
  source: string;

  /** Content status indicating the level of text retrieved */
  contentStatus?: ContentStatus;

  /** Extracted and cleaned paper text (full text or abstract) */
  text?: string;

  /** Prepared text chunks ready for vector indexing / RAG */
  chunks?: PaperChunk[];

  /** Non-fatal retrieval error if retrieval was attempted and failed */
  retrievalError?: string;
}

/**
 * Summary of paper retrieval and chunking statistics.
 */
export interface RetrievalSummary {
  totalPapers: number;
  fullTextCount: number;
  abstractOnlyCount: number;
  metadataOnlyCount: number;
  totalChunks: number;
}

/**
 * Output shape for the Query & Search Agent (Research Discovery Agent).
 */
export interface QuerySearchResult {
  /** The original user query */
  query: string;

  /** Search queries generated by the agent */
  searchQueries: string[];

  /** Deduplicated list of papers found */
  papers: ResearchPaper[];

  /** Errors encountered during search (non-fatal) */
  errors?: string[];

  /** Summary of retrieval & preparation results */
  retrievalSummary?: RetrievalSummary;
}
